### ISSUE TITLE
ropstar terminates at getting libc version

### ISSUE THREAD

**Issue by TarushS** [xct/ropstar#6]
```
[+] Leak puts : 0x7fc29146c040
[*] Saved leak
[*] Stopped process '/home/tarush/tools/ropstar/baby_boi' (pid 5748)
[*] Getting libc version
[*] /home/tarush/tools/libc-database/find puts 040 
[*] []
tarush@core:~/tools/ropstar$
```
I have installed libc-database in ~/tools/ but getting this error
Target binary: [baby_boi](https://github.com/osirislab/CSAW-CTF-2019-Quals/blob/master/pwn/baby_boi/baby_boi)

**Comment by xct** [comment]
I tested the target binary and it can be solved with ropstar, I assume you are missing the correct libc version in your libc-database. Have you added your local libc versions ?

**Comment by TarushS** [comment]
`[DEBUG] [b'Hello!', b'Here I am: 0x7ff27542eb40', b'P\xe0Du\xf2\x7f', b'Hello!', b'Here I am: 0x7ff27542eb40']                                                                              
[+] Leak puts : 0x7ff27544e050                                                                                                                                                              
[*] Saved leak                                                                                                                                                                              
[*] Stopped process './baby_boi' (pid 14421)                                                                                                                                                
[*] Getting libc version                                                                                                                                                                    
[*] /root/tools/libc-database/find puts 050                                                                                                                                                 
[*] ['libc6_2.12.1-0ubuntu10.4_amd64']
Getting libc6_2.12.1-0ubuntu10.4_amd64
  -> Location: http://old-releases.ubuntu.com/ubuntu/pool/main/e/eglibc//libc6_2.12.1-0ubuntu10.4_amd64.deb
  -> Downloading package
Failed to download package from http://old-releases.ubuntu.com/ubuntu/pool/main/e/eglibc//libc6_2.12.1-0ubuntu10.4_amd64.deb
cp: cannot stat '/root/tools/libc-database/libs/libc6_2.12.1-0ubuntu10.4_amd64/libc.so.6': No such file or directory`
Even after reinstalling libc-database and ropstar, this still happens and couldn't get a shell.

**Comment by xct** [comment]
Can you try again with the latest update (just pushed a small one)? If it is not working, go to the libc-database folder and make sure the library is really added (must be in ./libs).
