### ISSUE TITLE
/bin/sh: 1: /root/tools/libc-database/find: not found

### ISSUE THREAD

**Issue by CoffeeNData** [xct/ropstar#8]
Just that. I'm running it on Python3.7.6

```
[DEBUG] [b'You know who are 0xDiablos: ', b'aaaabaaacaaadaaaeaaafaaagaaahaaaiaaajaaakaaalaaamaaanaaaoaaapaaaqaaaraaasaaataaauaaavaaawaaaxaaayaaazaabbaabcaabdaabeaabfaabgaabhaabiaabjaabkaablaabmaabnaaboaabpaabqaabraabsaabtaabuaabvaabp\x90\x04\x08\x1e\x90\x04\x08\x1c\xc0\x04\x08\xb1\x92\x04\x08', b'\x103\xdf\xf7\x86\x90\x04\x08 W\xda\xf7P9\xdf\xf7\xb6\x90\x04\x08\xf0\xa9\xe4\xf7', b'You know who are 0xDiablos: ']
[+] Leak puts : 0xf7df3310
[*] Saved leak
[*] Stopped process './vuln' (pid 15742)
[*] Getting libc version
[*] /root/tools/libc-database/find puts 310 
/bin/sh: 1: /root/tools/libc-database/find: not found
[*] []
```

I tryed running it as root and as a normal user, both with the proper installation of the **requirements.txt** file.

**Comment by xct** [comment]
Looks like /root/tools/libc-database/find does not exist, are you sure its there?

**Comment by CoffeeNData** [comment]
I've made some more research and found the libc-database repository. Just placed it in the correct path. Lets see if it work now :)

**Comment by CoffeeNData** [comment]
Ok, the database error is fixed now, but I have another issue: 

´´´[DEBUG] [b'You know who are 0xDiablos: ', b'aaaabaaacaaadaaaeaaafaaagaaahaaaiaaajaaakaaalaaamaaanaaaoaaapaaaqaaaraaasaaataaauaaavaaawaaaxaaayaaazaabbaabcaabdaabeaabfaabgaabhaabiaabjaabkaablaabmaabnaaboaabpaabqaabraabsaabtaabuaabvaabp\x90\x04\x08\x1e\x90\x04\x08\x1c\xc0\x04\x08\xb1\x92\x04\x08', b'\x10S\xd6\xf7\x86\x90\x04\x08 w\xd1\xf7PY\xd6\xf7\xb6\x90\x04\x08\xf0\xc9\xdb\xf7', b'You know who are 0xDiablos: ']
[+] Leak puts : 0xf7d65310
[*] Saved leak
[*] Stopped process '/home/reshi/Documents/HTB/vuln' (pid 5798)
[*] Getting libc version
[*] /root/tools/libc-database/find puts 310 
grep: db/*.symbols: No such file or directory
[*] []
´´´

**Comment by xct** [comment]
This has probably nothing to do with ropstar, looks like a libc-database issue.

**Comment by CoffeeNData** [comment]
Ok, I will check it in a couple hours
